# 
# 
# 
PROJECT     =  "Chachoengsao"
LDP =  ["TM" ,"101:25" ]    # longitude in degree and minute ! for central merdian
#LDP =  ["LCC" ,"13:34" ]    # longitude in degree and minute ! for single standard parallel
#OFFSET_PP   =  +100            # m
FALSE_EN    = 'AUTO'        # make coordinate look nice , compact and easier to handle

[TEST_POINT]
GPCK  = ['./CACHE/PointMSL Chachoengsao.gpkg','Point']   # centroid of the constuction site

[UTM_LDP]
PROJ='EPSG:32647'
#RTK1=[ 783582.86, 1647318.61, 123.0 ]
#RTK2=[ 783622.71, 1647262.97, 456.0 ]

[LDP_UTM]
PROJ='EPSG:32647'
#BLDG-1=[ 5200.000, 5300.000, 260.0 ]
#BLDG-2=[ 5225.000, 5300.000, 260.0 ]
#BLDG-3=[ 5225.000, 5400.000, 260.0 ]
#BLDG-4=[ 5200.000, 5400.000, 260.0 ]
